extends:
  - plugin:import/typescript
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: 'tsconfig.json'
plugins:
  - '@typescript-eslint'
  - eslint-plugin-import
rules:
  import/named: error
